### ISSUE TITLE
How to add some code to generated classes?

### ISSUE THREAD

**Issue by pavlm** [goetas/xsd2php#100]
For two properties in some class (name, lastName) i want to inject calculated getter method getFullName() { return $this->getName() . ' ' . $this->getLastName() } when generating.
And of course subsequent generation calls will produce this method.
Is that possible?

**Comment by goetas** [comment]
Unfortunaltley this feature it is not available. The best way to do it is to allow "plugins" for each kind of reader (YAML or PHP). This will allow user-land features.

**Comment by goetas** [comment]
i will consider this currently as out of scope.. feel free to re open it is (better to create a pull request :) )
