### ISSUE TITLE
Annotations JMS 

### ISSUE THREAD

**Issue by MI-LA01** [goetas/xsd2php#101]
Hello @goetas 

a quick question, is there a magic way to output all JMS annotations during the PHP Class generation ?

**Comment by goetas** [comment]
Unfortunately there is not an easy way to do it.

The logic to generate PHP classes is quite complex, and the logic to generate JMS information it is also quite complex.

An idea can be to inject annotations in a second step (once php metadata are ready...), but to me it looks not worth. I think JMS yaml files are good enough.

**Comment by goetas** [comment]
out of scope for now sine YAML files are working pretty well
