### ISSUE TITLE
Tag (stable) version

### ISSUE THREAD

**Issue by holtkamp** [goetas/xsd2php#109]
It has been some time a (stable) version has been tagged, requiring us to use ```dev-master``` in ```composer.json```...

**Comment by goetas** [comment]
sounds a good idea... a year ago i planned to move everything to https://github.com/goetas-webservices
and start tagging the lib with a new name and start with 0.1.0 (0.x releases allow BC breaks... and become 1.0 when will be possible to use the official serializer )

**Comment by goetas** [comment]
https://github.com/goetas/xsd2php/releases/tag/2.0.0
