### ISSUE TITLE
Symfony dependency

### ISSUE THREAD

**Issue by iwex** [goetas/xsd2php#113]
This 'symfony/symfony' dependency brokes Laravel 'optimize --force' command. Could you please use particular symfony packages instead of general symfony package?

**Comment by davidhemphill** [comment]
This has been breaking my Laravel project and making it to where I haven't been able to deploy. Our deploy process runs `php artisan optimize --force` command. Please fix this as soon as possible.

**Comment by goetas** [comment]
solved in https://github.com/goetas/xsd2php/commit/ae8cda91719efd5e0724e7bd5a841fb110523219
