### ISSUE TITLE
Typo in program output ("namepsace")

### ISSUE THREAD

**Issue by vnen** [goetas/xsd2php#115]
It's written "namepsace" instead of "namespace" in [this file](https://github.com/goetas/xsd2php/blob/ae48a006893c44bd4cd1cd96aa7c78618381ca73/lib/Command/AbstractConvert.php#L74) (twice in line 74 and once in line 86).

**Comment by goetas** [comment]
pull request is welcome

**Comment by goetas** [comment]
see https://github.com/goetas/xsd2php/issues/124
