### ISSUE TITLE
GoetasWebservices\Xsd\XsdToPhpRuntime\Jms\Handler\BaseTypesHandler does not exist anymore?

### ISSUE THREAD

**Issue by KalebClark** [goetas/xsd2php#116]
I am using authorize.net PHP SDK that requires this package. I am getting an error that this class does not exist, and I cannot find it where it should belong in this package.

Am I just doing something wrong here, or has this been removed?

Thank you,
-Kaleb

**Comment by doppioandante** [comment]
Ditto

**Comment by goetas** [comment]
this is explained in https://github.com/goetas/xsd2php#serialize--unserialize
