### ISSUE TITLE
Metadata Issue

### ISSUE THREAD

**Issue by victorgp89** [goetas/xsd2php#123]
/**
 * Class representing HotelMealPlansNotifRSType
 *
 *
 * XSD Type: HotelMealPlansNotifRS
 */
class HotelMealPlansNotifRSType extends Controller
{

}

Is it possible not to add the properties of the parent class to the metadata?

**Comment by goetas** [comment]
This project is deprecated, please open issues on https://github.com/goetas-webservices/xsd2php

> Is it possible not to add the properties of the parent class to the metadata?

The behavior is completely inferred from the XSD (of course there are many limitations in what can be expressed in PHP), so it your class extends "controller", will have the properties available in "controller"

Does this answer?
