### ISSUE TITLE
Keeping the order of a mixed sequence

### ISSUE THREAD

**Issue by tstumm** [goetas/xsd2php#127]
Hi,

I'm currently working on a project where a complex type may contain a sequence of mixed types, i.e.
```            
<choice maxOccurs="unbounded">
    <element name="label" type="ns:labelType"/>
    <element name="text" type="ns:textType"/>
    <element name="select" type="ns:selectType"/>
    <element name="checkbox" type="ns:checkboxType"/>
 </choice>
```

The generated classes nicely group them into different attributes BUT I really need to keep track of the actual order of those in the XML I'm parsing. Is there any way to do this using xsd2php?

**Comment by tstumm** [comment]
Oops, used the wrong repository to file this.

**Comment by goetas** [comment]
The issue should be moved to https://github.com/goetas-webservices/xsd-reader

**Comment by tstumm** [comment]
See https://github.com/goetas-webservices/xsd-reader/issues/41
