### ISSUE TITLE
using substitutionGroup to alias jms serialized_name

### ISSUE THREAD

**Issue by richardhdc** [goetas/xsd2php#128]
I have a germal xml and I need to convert it to english then de-serialize it using jms. The problem is that, if I use substitutionGroup the jms yml file does not get element properly. I tested changing the serialized_name to the german word and everything works. How can I create an xsd that will make my jms yml file working with german xml at the same time the accessors are in english?

**Comment by goetas** [comment]
Hi, 
two things: 
1. As you can read [here](https://github.com/goetas/xsd2php), this repo is deprecated, you should create tickets into [this](https://github.com/goetas-webservices/xsd2php) repo
2. Your issue looks a very specific question that goes outside of the scope of this library but more related to the business you are dealing with. You can find my contacts [here](https://www.goetas.com/) and eventually we can discuss specific solutions for you at my consulting rate
