### ISSUE TITLE
Does it work with a WSDL file as well?

### ISSUE THREAD

**Issue by dersteve** [goetas/xsd2php#52]
I was wondering if it also works with a WSDL - instead of a separate XSD?

Of course I could extract the XSD from the WSDL, but I would like to skip that manual step.

Any ideas, tutorials, pull-requests? Or is this just out of scope for this project?

**Comment by holtkamp** [comment]
I also encountered this doubt, the documentation currently states:

"With goetas/xsd2php you can convert any XSD/WSDL definition into PHP classes."

So maybe put a remark there and explain the limitation?

Oh, and in case WSDL support is considered, loading them from a remote location would be nice, something like:

```
php bin/xsd2php convert:php https://extdev.seqr.com/soap/merchant/cashregister-2?wsdl=ERSWSExternalClientService.wsdl --ns-map='http://external.interfaces.ers.seamless.com/;Seamless/' --ns-dest='Seamless/;src/'
```

I now extracted the XML Schema part into a local file and generated from there.

**Comment by goetas** [comment]
You can convert it programmaticaly, extracting the XSD node from the WSDL.
Using the console command this is not possible.

**Comment by fbrier** [comment]
It would be nice if a wsdl2php implementation was compatible with your yml approach and the object you generate.  Even having methods able to set the XML or objects into the web service request or out of the response would be cool.  I am going to have to do this tomorrow.

**Comment by holtkamp** [comment]
@fbrier the problem is that there are various ways to include XML Schema definitions in a WSDL document. From what I know:

- include in case of same namespace: <include schemaLocation="anyURI" />
- import in case of different namespace: <import namespace="namespaceAnyURI" schemaLocation="schemaAnyURI" />
- inline definitions, so in the WSDL itself, include the XSD statements, ``` <wsdl:types><xsd:schema xmlns=""> ...</xsd:schema></wsdl:types>```

So as you can see, complete support to extract the XSD from the WSDL automagically is a challenge. I *do* suggest to change [this misleading line](https://github.com/goetas/xsd2php/blame/master/README.md#L10) in the documentation.

**Comment by goetas** [comment]
This https://github.com/goetas-webservices/wsdl-reader should be the solution.

Is still WIP, but more or less is working

**Comment by fbrier** [comment]
It isn't quite clear to me what the wsdl-reader is.  It seems like it reads in a wsdl and allows you to traverse the metadata that describes it.  Please correct me if I am wrong.  The tool that I was looking for was a SoapClient and possibly server that would utilize the classes generated by xsd2php.  I would have to study it more, but it appears that the PHP library class SoapClient has the ability to map the schema elements to the PHP objects.  If you search down in the doc for the 'classmap' option on http://php.net/manual/en/soapclient.soapclient.php .  It appears that you can provide an array/map and SoapClient will use it.  So could a method traverse the generated .yml files and create that array?  Would it work?  Just a thought.

**Comment by goetas** [comment]
@fbrier you are right. What i'm trying to do with https://github.com/goetas-webservices is to build a pure php alternative for http://php.net/manual/en/soapclient.soapclient.php

**Comment by fbrier** [comment]
Is there a similar way to generate the PHP classes from the WSDL similar to how xsd2php works?  Or the project is not that far yet?  Just asking.  It would be nice to populate the PHP objects and then use the serialize and "new \SoapVar($params_xml, XSD_ANYXML)".  Then all the namespacing gets baked in.  Thank you.

**Comment by goetas** [comment]
the problem is solved by https://github.com/goetas-webservices/xsd2php

that is a complete refactoring of the project including many other components, see https://github.com/goetas-webservices
