### ISSUE TITLE
help with serialization of simple AType objects - do I need custom handler?

### ISSUE THREAD

**Issue by zevnikrok** [goetas/xsd2php#57]
First of all congratulations for a great project you've made. With xsd2php writing xmls feels much more enteprise like:)

Unfortunatelly I have a problem with what I think is very simple schema. When serializing it to XML, some elements behave like they were not recognized by the yaml file.
Do I need a custom handler for this kind of situations?

If somebody could help me with writing custom handler / managing this schema, I'd be grateful.

This is the output:

    <Job xmlns="http://www.trogon.si/Schemas/2010/JobXML/2.0">
      <Item>
        <Price>
          <gross>100</gross> 
        </Price>
      </Item>
    </Job>

Job.AType.PriceAType.yml looks OK:

    Trogon\JobXML\Job\AType\PriceAType:
        properties:
            gross:
                expose: true
                access_type: public_method
                serialized_name: Gross
                xml_element:
                    namespace: 'http://www.trogon.si/Schemas/2010/JobXML/2.0'
                accessor:
                    getter: getGross
                    setter: setGross
                type: float

Here is the sample code:

    $xml = new \Trogon\JobXML\Job();
    $item = new \Trogon\JobXML\Item();
    $price = new \Trogon\JobXML\Item\PriceAType();
    $price->setGross(100);
    $item->setPrice($price);
    $xml->addToItem($item);
    
    $sb = SerializerBuilder::create();
    $sb->addMetadataDir(ROOT_PATH . '/library_external/Trogon/JobXML', 'Trogon\JobXML');
    $sb->configureHandlers(function (\JMS\Serializer\Handler\HandlerRegistryInterface $h) use ($sb) {
    $sb->addDefaultHandlers();
    $h->registerSubscribingHandler(new \Goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler()); // XMLSchema List handling
    $h->registerSubscribingHandler(new \Goetas\Xsd\XsdToPhp\Jms\Handler\XmlSchemaDateHandler()); // XMLSchema date handling
    // $h->registerSubscribingHandler(new YourhandlerHere());
    });
    $ser = $sb->build();
    file_put_contents('c:/test.xml', $ser->serialize($xml, 'xml'));

And schema:

    <?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:job="http://www.trogon.si/Schemas/2010/JobXML/2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.trogon.si/Schemas/2010/JobXML/2.0" elementFormDefault="qualified">
    	<xs:element name="Job">
    		<xs:complexType>
    			<xs:sequence>
    				<xs:element ref="job:Item" minOccurs="0" maxOccurs="unbounded"/>
    			</xs:sequence>
    		</xs:complexType>
    	</xs:element>
    	<xs:element name="Item">
    		<xs:complexType>
    			<xs:sequence>
    				<xs:element name="Price">
    					<xs:complexType>
    						<xs:sequence>
    							<xs:element name="Gross" type="xs:decimal"/>
    						</xs:sequence>
    					</xs:complexType>
    				</xs:element>
    			</xs:sequence>
    		</xs:complexType>
    	</xs:element>
    </xs:schema>

**Comment by zevnikrok** [comment]
I see there is a problem with naming of yaml files:
-php generated patch expects yaml definitions in Item.PriceAType.yml
-but the generated definitions are in Job.AType.PriceAType.yml

Manually renaming the files, solves the issue.

**Comment by goetas** [comment]
Fixed :smile:
