### ISSUE TITLE
TypeException (Can't find type named {http://www.opengis.net/gml/3.2}#anyType) for gml 3.2.1 xsd

### ISSUE THREAD

**Issue by durtlterbi** [goetas/xsd2php#58]
it seems this cannot handle type named "anyType" for gml 3.2

> xsd2php-master/bin/xsd2php convert:php \
> 'http://schemas.opengis.net/gml/3.2.1/gml.xsd' \
> --ns-map='http://www.opengis.net/gml/3.2;gml/3.2' \
> --ns-dest='gml/3.2;gml/3.2'

[Goetas\XML\XSDReader\Exception\TypeException]
Can't find type named {http://www.opengis.net/gml/3.2}#anyType, at line 21 in http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd

[Goetas\XML\XSDReader\Schema\Exception\TypeNotFoundException]
Can't find the Type named {http://www.opengis.net/gml/3.2}#anyType.

**Comment by goetas** [comment]
Just a hint, php namespaces can not contain `.`.

**Comment by goetas** [comment]
I used this:
```sh
bin/xsd2php convert:php 'http://schemas.opengis.net/gml/3.2.1/gml.xsd' \
--ns-map='http://www.opengis.net/gml/3.2;gml/' \
--ns-dest='gml/;gml/32/' \
--ns-map='http://www.isotc211.org/2005/gmd;gmd/' \
--ns-dest='gmd/;gml/32/' \
--ns-map='http://www.isotc211.org/2005/gco;gco/' \
--ns-dest='gco/;gml/32/' \
--ns-map='http://www.isotc211.org/2005/gts;gts/' \
--ns-dest='gts/;gml/32/' \
--ns-map='http://www.isotc211.org/2005/gsr;gsr/' \
--ns-dest='gsr/;gml/32/' \
--ns-map='http://www.isotc211.org/2005/gss;gss/' \
--ns-dest='gss/;gml/32/' \
--ns-map='http://www.w3.org/1999/xlink;xlink/' \
--ns-dest='xlink/;gml/32/' \
```

Of course i suggest you to use different folder for different namespaces
