### ISSUE TITLE
howto disable cdata ?

### ISSUE THREAD

**Issue by michabbb** [goetas/xsd2php#64]
is there any chance to disable CDATA globally ? doing this at each [element](http://jmsyst.com/libs/serializer/master/reference/annotations#xmlelement) is no solution... ;(

**Comment by michabbb** [comment]
or asked in a different way: is there any way to set for each class/element [annotations](http://jmsyst.com/libs/serializer/master/reference/annotations) while doing the xsd -> php generation ?

**Comment by goetas** [comment]
Why do you need to disable CDATA? From the XML prospective, CDATA and "normal text" are the same thing with just a different reppresentation...

**Comment by michabbb** [comment]
your are totally right ;) tell this the guys who made this API: http://download1.parallels.com/Plesk/Doc/de-DE/online/plesk-api-rpc/

so stupid they don´t accept CDATA.... thats why i am asking if there is somewhere a global switch for that.....

**Comment by goetas** [comment]
:(
unfortunately the lib does not allow this at the moment... feel free to create a PR for this.

Hint: [here](https://github.com/goetas/xsd2php/blob/master/lib/Jms/YamlConverter.php#L404) you have to add the 'cdata=fase' option somewhere. See also the [JMS Serializer](http://jmsyst.com/libs/serializer/master/reference/yml_reference) docs

Of course this should be a command line option

**Comment by michabbb** [comment]
i found somehwere a piece of code that fits perfect to my needs:

````php
$newXml = preg_replace("/" . preg_quote('<![CDATA[', '/') . "(.*?)" . preg_quote(']]>', '/') . "/mis", "\\1", $newXml);
````

better than nothing ;)

**Comment by goetas** [comment]
... a bad solution... but of course it works!

**Comment by michabbb** [comment]
i know.... ;(

**Comment by norbineogen** [comment]
namespace MyBundle\Model;

use JMS\Serializer\Annotation as Serializer;

/**
 * @Serializer\XmlRoot("job")
 */
class Job
{
    /** @var  int
     *  @Serializer\Type("int")
     *  @Serializer\XmlElement(cdata=false)
     */

    public $id;
    /** @var  string
     *  @Serializer\Type("string")
     *  @Serializer\XmlElement(cdata=false)
     */
    public $name;
    /** @var  string
     *  @Serializer\Type("string")
     *  @Serializer\XmlElement(cdata=false)
     */
    public $company;
......
}

**Comment by xgin** [comment]
Just for reference, the issue was resolved here: https://github.com/goetas-webservices/xsd2php/pull/89

The following configuration works for me:
```
  configs_jms:
    xml_cdata: false
```

**Comment by goetas** [comment]
Thanks for commenting on this!
