### ISSUE TITLE
Converting XML to PHP only worked with empty cache

### ISSUE THREAD

**Issue by Metabor** [goetas/xsd2php#69]
I am trying to import XML-Files using Symfony, XSD and the PHP-Objects and Metadata for JMSSerializer that are generated by this library.
When I unserialize a XML the first time with an empty cache the object is build like expected.
When I then import the same or an other XML file, only the root object is build and filled with data.
After deleting the cache it worked again for one time.

I first tried it with the patched JMSSerializer you provided, that resultes in this issue. I then checked out the original dev-master that was having the issue, but also with cleaned cache.

It seems that something from yout patch got lost when the cache is build.
Is this some known problem?
Any idea how I can solve this?

**Comment by goetas** [comment]
Hmmmm... i will investigate on this

**Comment by goetas** [comment]
Can you update my fork of jms serializer? [This](https://github.com/goetas/serializer/commit/24598efd7b1057cef8179a670e84330131709070) should fix it.

If does not work, let me know and I will re-open the issue

**Comment by Metabor** [comment]
Thanks. Works well and solved the problem.
