### ISSUE TITLE
Public vs Private

### ISSUE THREAD

**Issue by michabbb** [goetas/xsd2php#70]
hi, it seems like default that all variables in the generated php classes are "private".
but this does not allow me to do something like:

$array = (array)$MyClass;

because all variables are private i will never get that working ;-(
is there a way to set variables in the generated php files to "public" ??

thanks

**Comment by goetas** [comment]
The private properties are for encouraging the [encapsulation](http://en.wikipedia.org/wiki/Encapsulation_%28object-oriented_programming%29).

The PHP feature of casting objects to array is not exactly a best practice (even if sometime works...).
