### ISSUE TITLE
Invalid class- and property-names

### ISSUE THREAD

**Issue by mikemeier** [goetas/xsd2php#84]
My XSD has something like:

```
<xsd:element name="XXX.ACCTINFO" type="LedgerBalance" />
```

That will generate:

```php
private $xXX.ACCTINFO = null;
```

The char "." is not allowed in properties, nor in ClassNames. Is there a way to handle this?

**Comment by goetas** [comment]
Is it valid as xml element name?
Il 06/ago/2015 12:09, "Mike Meier" <notifications@github.com> ha scritto:

**Comment by mikemeier** [comment]
Yes it is.

**Comment by mikemeier** [comment]
Thanks a lot!

**Comment by mikemeier** [comment]
@goetas ClassNames are corrected now. But property names on the classes not:

```php
private $xXX.MSGS = null;
```

**Comment by mikemeier** [comment]
Great thanks!
